#!/usr/bin/env node
// PreToolUse hook (Edit|Write|MultiEdit).
// Blocks edits to files that must never be changed by an agent: secrets, VCS internals,
// lockfiles (generated by npm) and Claude's own guardrails. Exit code 2 = block; stderr goes back to Claude.
import { readFileSync } from 'node:fs';

let input;
try {
  input = JSON.parse(readFileSync(0, 'utf8'));
} catch {
  process.exit(0); // unreadable input: do not block
}

const filePath = String(input?.tool_input?.file_path ?? '').replaceAll('\\', '/');
if (!filePath) process.exit(0);

const rules = [
  { test: /(^|\/)\.env(\.(?!example$)[^/]+)?$/, why: 'environment files may hold secrets (edit .env.example instead)' },
  { test: /(^|\/)\.git\//, why: 'git internals' },
  { test: /(^|\/)package-lock\.json$/, why: 'generated by npm; change package.json and run npm install' },
  { test: /\.(pem|key|p12|jks)$/, why: 'key material' },
  { test: /(^|\/)secrets\//, why: 'secrets directory' },
  { test: /\.tfstate(\.backup)?$/, why: 'Terraform state may contain secrets' },
  { test: /\.tfvars$/, why: 'Terraform variable files may contain secrets' },
  { test: /(^|\/)\.claude\/(settings\.json|hooks\/)/, why: 'Claude guardrails; the owner edits these by hand' },
];

for (const { test, why } of rules) {
  if (test.test(filePath)) {
    console.error(`Blocked: ${filePath} is protected (${why}). Ask the owner to make this change manually.`);
    process.exit(2);
  }
}
process.exit(0);
